services:
  app:
    restart: always
    build:
      context: ./
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./src

  db:
    image: postgres
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: example

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80