services:
  app:
    build:
      context: ./
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ./src

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
  
  tailwind:
      build:
        context: ./
        dockerfile: Dockerfile.TailwindV4
      volumes:
        - ./src:/app/src
      tty: true