FROM node:latest

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY tailwind.config.js ./

RUN yarn

RUN yes | npx @tailwindcss/cli

CMD ["npx","@tailwindcss/cli", "-i", "./src/static/input.css", "-o", "./src/static/output.css", "--watch"]