services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    restart: always
    volumes:
      - ./frontend/app:/frontend/app
      - ./frontend/public:/frontend/public
    env_file:
      - .env

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    env_file:
      - .env
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./backend

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80