services:
  app:
    build:
      context: ./
    env_file:
      - .env

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
      - 8405:8405

  # nginx:
  #     image: nginx:latest
  #     volumes:
  #       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     ports:
  #       - 80:80