FROM node:20-alpine

WORKDIR /frontend

COPY frontend/package.json ./
COPY frontend/yarn.lock ./
COPY frontend/postcss.config.mjs ./
COPY frontend/tsconfig.json ./
COPY frontend/next.config.ts ./

RUN yarn


CMD [ "yarn", "dev" ]

EXPOSE 3000